### ISSUE TITLE
Eliminacja powtarzających się wyrazów

### ISSUE THREAD

**Issue by fmichalski03** [fmichalski03/Text_Transformer#6]
## Jako użytkownik mogę eliminować powtarzające się wyrazy w bezpośrednim sąsiedztwie (Wyślij do do mnie wiadomość -> Wyślij do mnie wiadomość)

- Zamiana dwóch powtarzających się wyrazów na jeden: do do -> do
- Zamiana dowolnej liczby powtarzających się wyrazów: do do do -> do
- Zamiana wszystkich powtórzeń w ramach tekstu: do do po po -> do po
- Działa prawidłowo dla wszystkich znaków UTF-8

### Podzadania:
- Implementacja funkcji eliminującej powtarzające się wyrazy
- Obsługa dowolnej liczby powtórzeń wyrazów
- Testowanie poprawności działania dla wszystkich znaków UTF-8

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented a new transformation to remove repeating words in direct proximity. This satisfies the requirement to eliminate repeating words as described in the criteria. The implementation handles multiple consecutive repeats and works for all UTF-8 characters.

You can review changes in this commit: https://github.com/jjyutm4532/fmichalski03-Text_Transformer-6/commit/c5e92fdd2316a49393526481d3dd4f6d98167ab9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
